### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by sjlagasse** [chuckwondo/codecademy-jamming#2]
https://github.com/chuckwondo/codecademy-jamming/blob/b6c80ac05f06fc6ac9db946c6a6f4fcc94fc6735/src/components/App/App.js#L30-L37

Haven't seen anyone bind their functions like his. It definitely will work!

**Comment by chuckwondo** [comment]
Yeah, I got tired of typing them all out, or even copying/pasting (which is error-prone).
