### ISSUE TITLE
Add and Remove

### ISSUE THREAD

**Issue by sjlagasse** [chuckwondo/codecademy-jamming#3]
https://github.com/chuckwondo/codecademy-jamming/blob/b6c80ac05f06fc6ac9db946c6a6f4fcc94fc6735/src/components/App/App.js#L57-L69

Hmm.. It seems like these will work? However, you are relying heavily on the `ramda` library you installed. I would suggest that you use plain JavaScript to handle these functions. 99% of employers will not be using the `ramda` library in their code.

**Comment by chuckwondo** [comment]
This certainly works. I was simply taking the opportunity to experiment with the ramda library to write some parts of my code in a functional style rather than standard JS style.

I could have written them this way using vanilla JS:

```javascript
  addTrack(track) {
    if (!this.state.playlistTracks.find(t => t.id === track.id)) {
      this.setState({
        playlistTracks: [...this.state.playlistTracks, track]
      })
    }
  }

  removeTrack(track) {
    this.setState({
      playlistTracks: this.state.playlistTracks.filter(t => t.id !== track.id)
    });
  }
```
