### ISSUE TITLE
Using Props

### ISSUE THREAD

**Issue by sjlagasse** [chuckwondo/codecademy-jamming#4]
https://github.com/chuckwondo/codecademy-jamming/blob/b6c80ac05f06fc6ac9db946c6a6f4fcc94fc6735/src/components/PlayList/Playlist.js#L16-L19

Good job using props here. However, it's hard to follow because I don't have experience with the library you are using.

**Comment by chuckwondo** [comment]
This is standard JS. What are you referring to here?
