### ISSUE TITLE
Overall Summary

### ISSUE THREAD

**Issue by sjlagasse** [chuckwondo/codecademy-jamming#6]
### Criteria 1: App Creation, Folder Structure, and File Paths
* _Score Level: 4/4 
* _Comment(s): You had all the right files and folder. Good job.
 
### Criteria 2: Correct Implementation of User Flows (e.g. Searching, Token Generation, Save Playlist, etc.)
* _Score Level: 4/4
* _Comment(s): Nice job conquering this part of the project!
 
### Criteria 3: Proper JavaScript and JSX Syntax and Formatting
* _Score Level: 4/4
* _Comment(s): You show a clear understanding of the React fundamentals. However, you are relying heavily on that library to do most of your JavaScript. While this might make things faster for you, I would suggest not using it moving forward as not many companies use it.

### Criteria 4: Implementation Adheres to DRY Principles
* _Score Level: 4/4
* _Comment(s): You reused components properly.
 
### Overall Score: 16/16

You did a great job on your project. Nice job using requests in your Spotify.js file and having the patience to figure out the hard parts. In your component files you did a great job using off you understand how to use React. Great job updating state, binding methods, using props, rendering children and more. Just make sure to focus more on native JS. All in all, great job on this project!

**Comment by chuckwondo** [comment]
Thanks so much for your review! Regarding the use of the ramda library and not sticking to vanilla JS everywhere, that was for my own practice in writing in a bit more of a functional style. I could have easily written it all in vanilla JS, but that would have been a bit boring :-)
